### ISSUE TITLE
Abbrechen der Anzeige der richtigen Antwort.

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_mooduell#10]
Abbrechen durch Klick oder ähnliches sollte möglich sein.

**Comment by georgmaisser** [comment]
Fixed wie besprochen: Nun kann eingestellt werden, dass die Antwort bis zum nächsten Klick des Users angezeigt wird, oder eine fixe Zeit (z.b. 10 Sekunden) kann mit Klick abgekürzt werden.
