### ISSUE TITLE
Ladebalken nachdem die Frage richtig beantwortet wurde

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#14]
Der Ladebalken soll während die richtige Antwort angezeigt wird, anzeigen, wie viel Zeit man hat um die richtige Antwort anzusehen. Also genauso wie das bei den Fragen gemacht ist. 

Wenn kein Zeitlimit eingestellt ist, kann man den Ladebalken natürlich weglassen oder voll lassen, sodass er nicht runterläuft.

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020
