### ISSUE TITLE
Spiel gegen zufälligen Gegner

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#15]
Es wäre gut, wenn man die Option hätte gegen einen zufälligen Gegner zu spielen. Genauso wie es schon bei der vorherigen Version möglich war.

Ich habe momentan nur Spiele starten können, wenn ich einen spezifischen Gegner auswähle.

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020
