### ISSUE TITLE
Einklappen der offenen Spiele

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#18]
Ist es möglich eine Option einzubauen, die die offenen Spiele einklappt?

Momentan kann es sehr unübersichtlich werden, wenn viele Spiele gleichzeitig offen sind.

**Comment by georgmaisser** [comment]
Ist glaub ich durch die seither eingeführte Anordnung (eigene Seiten für beendete und waiting spiele hinfällig)?
