### ISSUE TITLE
Farbe richtige Antwort

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#19]
Wenn eine Frage falsch beantwortet wird und dann die richtige Antwort angezeigt wird, wird dies in der Farbe orange angezeigt. Kann man das vielleicht auf grün ändern, damit klarer ist, dass das die richtige Antwort ist?

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020 (ich bin für weitere Vorschläge, wie das am besten signalisiert werden kann, dankbar)
