### ISSUE TITLE
Übersicht Sieg/Niederlage anzeigen

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#20]
Kann man in der Übersicht bei den beendeten Spielen anzeigen, ob man gewonnen/verloren hat?

Momentan muss man noch zuerst auf das Spiel drücken und auch dann muss man die "Hackerl" zählen um zu sehen wer gewonnen hat.

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020
