### ISSUE TITLE
Pseudonym

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#21]
Bei erstmaligem Login wird zwingend ein Pseudonym verlangt:
1) Wenn man auf "Abbrechen" drückt wird man ohne Warnung wieder aus geloggt.
2) Wenn man auf "Fertig" drückt ohne ein Pseudonym einzugeben wird zwar das Popupfenster geschlossen man kann allerdings keine Spiele starten sondern wird wieder auf das Profil mit dem Popup zur Pseudonym-Eingabe weitergeleitet.

Wenn man bereits ein ein Pseudonym gesetzt und im Profil auf Pseudonym ändern geht kann man dies "zurücksetzen" indem man keinen Inhalt ins Textfeld eingibt, das heißt danach passiert der gleiche Ablauf wie oberhalb beschrieben.

**Comment by georgmaisser** [comment]
Danke. Das ist jetzt einmal das gewünschte Verhalten, denn ohne Pseudonym kann das Spiel nicht gespielt werden, WENN das in den Settings so verlangt wird. Vielleicht besprechen wir, welches Verhalten Ihr gerne hättet.

**Comment by georgmaisser** [comment]
im nächsten Update gefixed
