### ISSUE TITLE
App-Login ohne vorherigen Kurs-Login

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#22]
1. Wenn man sich in die App einloggt ohne vorher einmal im Kurs eingeloggt gewesen zu sein, bekommt man nur die Fehlermeldung ("Etwas ist schief gegangen. Bitte starte die App neu!") ohne Hinweis das man sich zuerst im dazugehörigen Moodle Kurs einloggen soll.
2. Was passiert in der App wenn ein Studierender nur Kurse besucht die nicht diese Aktivität nützen, sich aber in der App anmeldet?

**Comment by georgmaisser** [comment]
Dieses Verhalten werde ich noch genauer ansehen bitte gerne auch Ratschläge, was passieren soll.

**Comment by georgmaisser** [comment]
Hab mal eine Lösung implementiert in der Version von Montag 23.11.
