### ISSUE TITLE
App Update

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#23]
Wenn man bereits zuvor zur Verfügung gestellte alt Version von MooDuell installiert hat, lässt sich die App bzw. das Update nicht installieren. Das heißt man muss die alte Version der App vorher löschen damit sich die neue installieren lässt.

**Comment by georgmaisser** [comment]
Das ist jetzt nur bei der Testversion so, das wird in Zukunft (auch schon bei der nächsten Testversion) natürlich nicht so sein.
