### ISSUE TITLE
Kontextmenü im Login Screen

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#24]
Durch einen swipe nach rechts lässt sich das Kontextmenü auch im Login Screen einblenden. Es werden leere Seiten für den Home Screen MooDuell und Bestenliste angezeigt. Erst beim Klick auf das Profil kommt die Fehlermeldung "Etwas ist schief gegangen. Bitte starte die App neu!"

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020
