### ISSUE TITLE
Neustart der App

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#25]
Wenn in der App etwas schief geht, wird der User durch die Fehlermeldung dazu aufgefordert die App neu zu starten. Könnte man diese nicht automatisch einfach neu starten mit vorhergehender Warnmeldung.

**Comment by georgmaisser** [comment]
Ich glaube, dass schon bald praktisch keine Fälle haben werden, wo ein Neustart wirklich notwendig sein wird oder wo so eine Fehlermeldung auftaucht. Vielleicht arbeiten wir eher noch am Wording, falls doch mal eineFehlermeldung auftaucht.

**Comment by georgmaisser** [comment]
ich mach das mal zu. wenn noch mal Notwendigkeit auftaucht, kann man es wieder anlegen.
