### ISSUE TITLE
Aufgeben

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#27]
Durch einen swipe nach links kommt bei offenen Spielen ein "Ich gebe auf!" Button, allerdings ohne Funktionalität.
Ist dies mit "Delete" in den bekannten Bugs gemeint?

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020 (ist ersatzlos rausgenommen. Aufgeben kann man jetzt über das Moodle Plugin)
