### ISSUE TITLE
Bestenliste - Pokal

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#28]
In der Bestenliste wird neben den Spielern ein Pokal angezeigt. Derzeit sind dort bei mir nur drei Teilnehmer eingetragen daher wie würde das ab dem vieren Platz aussehen? Außerdem wenn man auf diesen Pokal tippt bekommt man ebenfalls die generische Fehlermeldung das etwas schief gegangen ist. Soll dieser Pokal überhaupt ein Button sein? Wenn ja, welche Funktionalität ist dafür vorgesehen?

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020 (Anzeige ab 4 besprechen wir noch)
