### ISSUE TITLE
Ladebalken bzw. weiterschalten bei Multiple Choice Fragen

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#29]
Wenn bei Multiple Choice Fragen die Zeit abgelaufen ist werden zwar die angegebenen Antworten als richtig oder falsch markiert, allerdings bleibt weiterhin das Overlay und es läuft ein Ladebalken, wenn man neben den Weiter-Button drückt stoppt/verschwindet der Ladebalken allerdings kommt man nur durch drücken auf den Weiter-Button zur nächsten Frage.

**Comment by georgmaisser** [comment]
fixed im APK vom 16.11.2020
