### ISSUE TITLE
Screen freezing bei manchen Fragen

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#31]
Leider war das Problem nicht wirklich reproduzierbar und tritt nicht immer auf, aber bei manchen Fragen friert der Bildschirm ein das heißt es läuft zwar der Countdown ab man kann aber auf keine Antwort drücken. 
Das weiterschalten zur nächsten Frage geht dann wieder. Das Problem trat sowohl beim Start eines neuen Spiels auf als auch mitten in einem Spiel, allerdings vermehrt bei der Frage: "Um ein bestehendes Quiz für MooDuell freizuschalten oder...". Anfänglicher Verdacht auf Fragen nach einer Multiple Choice Frage hat sich leider auch nicht bestätigen lassen.

**Comment by georgmaisser** [comment]
ich schau mir das noch genauer an. hatte ich bisher noch nicht.

**Comment by LinhartE** [comment]
Interessant, bei mir trat das bei fast allen Spielen die ich ausprobiert habe bei zumindest einer Frage auf.

**Comment by georgmaisser** [comment]
Gefunden. fixed in der Version vom 25. 11. 2020 (kommt heute noch)
