### ISSUE TITLE
Bestenliste

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#32]
1. Das zentrieren auf "mich" ist echt nice geworden funktioniert allerdings nicht bei jedem Aufruf von der Bestenliste. 
2. Bei mehreren Aktivitäten auf welche davon werde ich dann zentriert? Auf die Erste?

**Comment by georgmaisser** [comment]
Ja, das funktioniert echt noch nicht so gut. Eigentlich muss es eigene Scrollbereiche für jedes Quiz geben. Ich bin davon kein Fan, hab aber noch keine bessere Lösung. Alternativen wären

- z.b. klick auf Titel, um auf sich selbst zu scrollen
- scroll nur auf das erste der Quizzes

**Comment by georgmaisser** [comment]
Fix mit Version vom 29.11.2020
