### ISSUE TITLE
Fixierte Tabellen Header

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#34]
1. Es verschwinden leider bei allen Seiten die Header wenn man scrollt. Was bei den meisten kaum ein Problem darstellt aber trotzdem "nice to have" wäre ist für die Bestenliste etwas ungünstig vor allem nachdem man jetzt auf sich selbst zentriert ist und so die Information in welcher Aktivität man sich befindet verloren geht wenn man nicht rauf scrollt. 
2. Außerdem ist es zumindest für mich überraschend das Überschriften komplett verschwinden wenn es keine Einträge dazu gibt. Wäre es eventuell möglich dies den User durch eine Einstellung entscheiden zu lassen?

**Comment by georgmaisser** [comment]
1. Ja, das werde ich noch ändern.
2. Ist schon geändert.

**Comment by georgmaisser** [comment]
Fix mit Version vom 29.11.2020
