### ISSUE TITLE
Beendete Spiele - Zurück Button

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#35]
Bei den Details zu den beendeten Spielen kommt der Button mit "Zurück zur Übersicht" mittels diesem kommt man allerdings nicht zurück zur Übersicht der beendeten Spiele was denk ich angedacht wäre sondern zurück zum Hauptmenü.

**Comment by georgmaisser** [comment]
Ja, stimmt. Das sollte anders sein. fixe ich.

**Comment by georgmaisser** [comment]
fixed in Version 25.11.2020
