### ISSUE TITLE
Suche nach Mitspielern

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#36]
Funktioniert nur bei manchen Wörtern werden Spieler obwohl nicht vorhanden und auch so in der Liste angezeigt nicht gefunden. Beispielsweise Daniel wird gefunden wenn man das D eingibt verschwindet aber wieder wenn man Da oder Daniel eingibt.

**Comment by georgmaisser** [comment]
Das ist deshalb, weil hier nur die Nicknames durchsucht werden, Daniel hat als Neckname nur "D" eingegeben. Da wird ein Parameter nicht übergeben, das fixe ich gleich.

**Comment by LinhartE** [comment]
Ok macht Sinn, wirkt nur als etwas seltsames Verhalten wenn bei Spielen bei denen die Klarnamen eingestellt sind diese angezeigt werden, dann aber bei der Suche nicht mehr gefunden werden können.

**Comment by georgmaisser** [comment]
Klar, das darf nicht sein!

**Comment by georgmaisser** [comment]
fixed in der Version vom 25. 11. 2020
