### ISSUE TITLE
Skalierung der Inhalte im Landscape Mode

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#37]
1. Einzelne Texte werden im Landscape Mode zu viel vergrößert während andere auf ihrer normalen Größe bleiben. 
2. Außerdem wird die Übersichtsseite sowohl beim Starten eines neuen Spiels als auch bei der Anzeige der Details von beendeten Spielen zu groß und man sieht eigentlich nur mehr die Überschrift mit dem Namen der Aktivität.
3. Sowohl im Normal als auch im Landscape Mode nehmen die Symbole für gewonnen, verloren und unentschieden zu viel Platz auf der beendete Spiele Seite ein. Diese eventuell unterhalb statt rechts des Textes platzieren.

**Comment by georgmaisser** [comment]
Ad 1 & 2: Landscape schalte ich ganz ab.
Ad. 3. da würde ich nur ungern etwas ändern, das ist das Standard-Aussehen.

**Comment by LinhartE** [comment]
Ad 2: Dies betrifft auch den normalen Modus und dort nur die Einträge der Listen als auch den Screen bei den Spiel Details.
Ad 3: Standard-Aussehen ist das die Symbole rechts neben dem Text sein müssen?
