### ISSUE TITLE
Highlighting im Kontextmenü

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#38]
1. Es bleiben im Kontextmenü die falschen Menüpunkte hervorgehoben wenn man eine Navigation anders als über das Kontextmenü selbst auslöst. Beispielsweise wenn man oben auf den Eintrag MooDuell drückt kommt man zurück zum Hauptmenü es bleibt aber immer noch die aktuelle Seite auf der man sich gerade befunden hat hervorgehoben. Gleiches gilt auch für den Zurück zur Übersicht Button in den Details zu den abgeschlossenen Spielen
2. Außerdem würde ich den MooDuell-Eintrag umbenennen beispielsweise in Neues Spiel starten damit dieser besser zu den anderen Einträgen im Kontextmenü passt.

**Comment by georgmaisser** [comment]
Ad 1: Ja, das fixe ich noch.
Ad 2: Guter Hinweis. Vielleicht "Spiele MooDuell", oder "Du bist dran" oder ähnliches? Besprechen wir später noch.

**Comment by georgmaisser** [comment]
Fixed in Version vom 25.11.2020
