### ISSUE TITLE
Zurück Taste in einem Spiel

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#39]
Soweit ich das sehe wird wenn man ein neues Spiel startet und nach der Auswahl eines Gegners die zurück Taste des Smartphones benützt ein neues Spiel für beide ausgewählte Gegner angelegt und man spielt gegen den zuletzt gewählten. Allerdings wird für das zuvor angelegte Spiel die erste Frage als falsch markiert. Wenn man innerhalb des Spiels die zurück Taste drückt oder die App schließt passiert dieses Verhalten nicht.

**Comment by georgmaisser** [comment]
Hm, das war mir zu schnell, besprechen wir noch, was Du das genau meinst.

Das Verhalten sollte so sein:

- Wird, während eine Frage angezeigt wird, die Zurück-Taste gewählt, so wird die aktuelle Frage als Falsch eingecheckt.
- Wird der Screen schwarz gemacht (App gewechselt, Standby) wird beim Zurückkommen die Frage eingecheckt, also bereits vorausgewählte Antworten werden übernommen. Sind die Antworten richtig, kann auch die Frage in so einem Fall noch als richtig gewertet werden.
- Die "Zurück"-Taste alleine legt nie neues Spiel an.

**Comment by georgmaisser** [comment]
Fix mit Version vom 29.11.2020
