### ISSUE TITLE
Fragezeichen bei Freunden

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#40]
1. Das Fragezeichen bei der Kategorie Freunde scheint ein Button ohne Funktionalität zu sein. Zumindest kommt beim drücken auf diesen wieder die generische Fehlermeldung.
2. Ist es beabsichtigt das dieses nur angezeigt wird solange man noch keine Freunde hinzugefügt hat?

**Comment by georgmaisser** [comment]
Das ist mir nur bisher nicht aufgefallen. Der Button sollte hier keine Funktion haben. Man kann auch ein anderes Symbol einfügen oder es ganz weglassen. Besprechen wir das noch

**Comment by LinhartE** [comment]
Dabei handelt es sich nicht um das Symbol links sondern rechts des Textes: "Noch kein/e SpielerIn in dieser Kategorie" und wird nur angezeigt wenn noch keine Freunde hinzugefügt wurden.

**Comment by georgmaisser** [comment]
Ja, ich hab es eh so verstanden. Funktion sehe ich hier eigentlich keine, daher würde ich alles so lassen, nur eben die Klick-Funktion entfernen. Können wir aber noch einmal besprechen.

**Comment by LinhartE** [comment]
Ich hätte ein Popup mit einer Beschreibung zu Freunden erwartet, kann aber eventuell auch weggelassen werden.

**Comment by georgmaisser** [comment]
fixed in der Version vom 25. 11. 2020 (vorerst weggelassen. wenn eine Beschreibung gewünscht wird, können wir das heute noch besprechen)
