### ISSUE TITLE
Aufgeben

### ISSUE THREAD

**Issue by LinhartE** [Wunderbyte-GmbH/moodle-mod_mooduell#41]
Implementierung funktioniert soweit ich das sehe, allerdings wäre eine Benachrichtigung darüber oder zumindest ein erneutes nachfragen ob man wirklich aufgeben möchte meiner Meinung nach gut. Man kann zwar über die beendeten Spiele sehen welche und das Spiele aufgegeben wurden allerdings werden die dort auch als verloren gekennzeichnet.

**Comment by georgmaisser** [comment]
Das ist aber in jedem Sport so, dass Spiele, die aufgegeben wurden, als verloren gezählt werden... im Detail kann man reinsehen und man sieht dann, dass die Fragen nicht fertiggespielt wurden. Kann ich natürlich noch ändern...

**Comment by LinhartE** [comment]
Das stimmt ich hatte nur in Erinnerung das wir letztes Mal besprochen haben das diese irgendwie gesondert gekennzeichnet werden.

**Comment by georgmaisser** [comment]
Ich hab das so verstanden, dass zwar das Spiel als verloren gewertet wird, dass aber die verbliebenen Fragen nicht automatisch als "falsch beantwortet" in die Statistik eingehen. Aber ich bin da offen für alle Alternativen.
