### ISSUE TITLE
Scrollen bei Profil

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#43]
Auf iOS kann man momentan bei Profil nicht Scrollen und deshalb die "Zeige inaktive Spiele" einstellen.

**Comment by georgmaisser** [comment]
Ok, da hatte ich ein anderes screen Format. schon geändert. ich warte noch die heutige Sitzung ab und lade dann eine neue Version hoch, wird bis Montag wahrscheinlich online sein u passen.
