### ISSUE TITLE
Fragen erstellen

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#5]
Wäre es möglich, direkt im jeweiligen Quiz einen Link einzurichten, wo man dann zu dem Menüpunkt "Question Bank" kommt um neue Fragen zu erstellen?
 Da der jetzige Weg um eine neue Frage zu erstellen sehr umständlich ist, bzw. für Leute die sich mit moodle nicht auskennen schwer zu finden ist.

LG Jakob

**Comment by georgmaisser** [comment]
Lieber Jakob, Im Tab "Fragen" ist nun der entsprechende Link hinzugefügt, und zwar gleich direkt in die Kategorien, die dem aktuellen Quiz hinzugefügt sind. ae0d70114b71326254f4d4cc3d106dd068c95920
