### ISSUE TITLE
Support "Display description on course page"

### ISSUE THREAD

**Issue by goggo24** [Wunderbyte-GmbH/moodle-mod_mooduell#59]
As a teacher
I would like to display the description on the course page in analogy to other moodle core plugins (e.g. assignment)
to give my students more information

![grafik](https://user-images.githubusercontent.com/16721900/161223051-0b66df67-699c-4231-a8cc-fb7d4df093ba.png)

This would be helpful.

**Comment by georgmaisser** [comment]
Fixed with f2bd8944c0f1ae89c17d074bcc4133b23b872caa
