### ISSUE TITLE
styles.css not specific enough.

### ISSUE THREAD

**Issue by purnendudash** [Wunderbyte-GmbH/moodle-mod_mooduell#71]
https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/blob/9911500e88b15585d0c52a8113c12e3f2100a95b/styles.css#L35

in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used.

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:

.path-mod-assign .filething {
   color: red;
}
Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

eg "span.adminsettingsflags" in your styles.css could clash with other things - please use something like ".path-mod-ivs . span.adminsettingsflags" or similar.

**Comment by georgmaisser** [comment]
Thank your for these important hints. We fixed it.
