### ISSUE TITLE
Incorrect use of camel case.

### ISSUE THREAD

**Issue by purnendudash** [Wunderbyte-GmbH/moodle-mod_mooduell#72]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/blob/9911500e88b15585d0c52a8113c12e3f2100a95b/lang/en/mooduell.php#L57

**Comment by georgmaisser** [comment]
Fixed that.
