### ISSUE TITLE
SQL coding style - Indentation

### ISSUE THREAD

**Issue by purnendudash** [Wunderbyte-GmbH/moodle-mod_mooduell#74]
Sql statement should follow this indentation style - https://moodledev.io/general/development/policies/codingstyle/sql#indentation

There are many of these instances.

https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/blob/9911500e88b15585d0c52a8113c12e3f2100a95b/classes/external.php#L1224

**Comment by georgmaisser** [comment]
Thx for that, we learned sth new! Fixed it everywhere.
