### ISSUE TITLE
include files should use defined('MOODLE_INTERNAL') || die(); 

### ISSUE THREAD

**Issue by purnendudash** [Wunderbyte-GmbH/moodle-mod_mooduell#76]
If a php file should not be loaded on it's own (class files etc) then you should be adding a check to:
defined('MOODLE_INTERNAL') || die();

at the top of the file.

https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/blob/9911500e88b15585d0c52a8113c12e3f2100a95b/classes/task/challenge_results_task.php#L17

**Comment by georgmaisser** [comment]
Hi,

In this case, I think the Moodle Internal check should explicitly not be included.

When we do add it, we get this error:

<img width="592" alt="Bildschirmfoto 2024-03-12 um 14 23 34" src="https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/assets/7524621/6e56f47f-b8ea-474f-8203-548251f8f149">

It refers e.g. to this discussion:
https://tracker.moodle.org/browse/MDLSITE-5967
