### ISSUE TITLE
Kindly use language String to support this

### ISSUE THREAD

**Issue by purnendudash** [Wunderbyte-GmbH/moodle-mod_mooduell#77]
This should fail for other languages. Rather we should support this via language string.

https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/blob/9911500e88b15585d0c52a8113c12e3f2100a95b/classes/tables/table_games.php#L101

**Comment by georgmaisser** [comment]
Thank you for pointing this out. We switched to the much better method for a formatted date:

userdate($game->timemodified, get_string('strftimedatetime', 'core_langconfig'));
