### ISSUE TITLE
Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by goggo24** [Wunderbyte-GmbH/moodle-mod_mooduell#86]
Durch den neuen TinyMCE ist der HTML-Tag für images anders aufgebaut und Bilder können für die App-Anzeige nicht erkannt/übernommenwerden. Es muss nach "img" aktuell gleich die src kommen, sonst wird das Bild nicht erkannt.

Workaround: HTML-Code anpassen mittels Atto
<img width="1027" alt="image_moduell" src="https://github.com/Wunderbyte-GmbH/moodle-mod_mooduell/assets/16721900/361e6b03-3af3-4456-a0f6-8d4fe986b548">

Wir verwenden aktuell - v2.1.3, 2023120500

**Comment by georgmaisser** [comment]
Hi Danke für den Hinweis. Wir schauen uns das an!

**Comment by georgmaisser** [comment]
Hi, ist jetzt gefixt. Danke noch mal für den Hinweis!
