### ISSUE TITLE
Weisser Bildschirm nach click auf "Zur Übersicht"

### ISSUE THREAD

**Issue by olemde** [Wunderbyte-GmbH/moodle-mod_mooduell#90]
Mehrere User haben den Effekt gemeldet. Der Bildschirm (iphone) ist eingefroren und blank weiss, sobald nach einer Fragerunde auf "Zur Übersicht" gewählt wird. 
Bislang konnte keine Prozedur gefunden werden, um diesen Zustand bewusst herzustellen

**Comment by cbadusch** [comment]
Welche Version der App wird bei Ihnen verwendet:  [u:mooduell](https://apps.apple.com/us/app/u-mooduell/id1596475094) oder [MooDuell](https://apps.apple.com/us/app/mooduell/id1598911543) ?
Gibt es weitere Infos wann das Problem vermehrt auftritt (Internetgeschwindigkeit etc.) um das Problem einzugrenzen?

**Comment by olemde** [comment]
Danke für die schnelle Reaktion. Die App V ist 1.0.7 - Wir haben nochmals versucht diese Situation herzustellen, allerdings erfolglos. Evtl. schliessen wir den Case ...

**Comment by georgmaisser** [comment]
Hallo @olemde , vielen Dank jedenfalls für die Meldung. Falls das Problem wieder auftaucht oder es sonstige Fragen gibt, meldet Euch bitte bei uns!
